### PR TITLE
hotfix for fixes #5 #3

### LINKED ISSUE #5: SteamCMD doesn't work
I used nearly the same docker-compose as given but the log gives me the following error:

image

### PR DESCRIPTION
**Pull request by motey**

### CODE REVIEW

**Comment by jkread** [comment]
Instead of making the change in run.sh where it will need to be done every time the server starts I've applied it to the Dockerfile where it only has to run once during the build process. Testing it now in jkread/arkserver:dev

**Comment by motey** [comment]
> Instead of making the change in run.sh where it will need to be done every time the server starts I've applied it to the Dockerfile where it only has to run once during the build process. Testing it now in jkread/arkserver:dev

tried that, but it didnt worked for me. but i could not figure out why :/ 
btw: Have you thought about to use something like https://hub.docker.com/r/cm2network/steamcmd as the base image and outsource steamcmd setup

**Comment by motey** [comment]
> where it only has to run once during the build process

btw, this runs pretty fast (1-3 seconds) if steamcmd is up 2 date. and if it is in run.sh, steamcmd will be keeped up 2 date.
so maybe its not too bad to put in in run.sh.

**Comment by jkread** [comment]
arkmanager already runs it as main of the launch

**Comment by motey** [comment]
closed as it looks like a "just for me bug and fix". must be sth. with my env.

**Comment by jkread** [comment]
No it was definitely an issue. Working it out right now.

**Comment by motey** [comment]
Ok, sorry for the back and forth. I will leave the thread now as i switched to a [custom image fork](https://github.com/motey/Ark-docker) based on https://github.com/TuRz4m/Ark-docker which was a little bit easier to adapt to my use case. 
Nevertheless thanks for your work :heart:

**Comment by jkread** [comment]
No problem. I looked at that one when I was first looking. More issues than I cared to deal with. Best of luck. I got this one fixed up now.

**Pull request closed without merging**
